---
title: "Welcome to Data Science <br> for Psychologists <br> `r emo::ji('cat')`"
author: "S. Mason Garrison <br> Assistant Professor  <br> Wake Forest University"
output:
  xaringan::moon_reader:
    css: "slides.css"
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: solarized-light
      countIncrementalSlides: false
      slideNumberFormat: ""
---

class: center, middle

# Data Science in R Workshop

---

class: middle

# Hour 1: Introduction to R and Data Manipulation with base R and the tidyverse

---

## Introduction to R and Data Science

...

---

## The tidyverse Ecosystem

...

---

## Data Manipulation with base R

...

---

## Data Wrangling with dplyr

...

---

## Reshaping Data with tidyr

...

---

## Hands-on Exercise: Data Manipulation

...

---

class: middle

# Hour 2: Data Wrangling and Transformation

---

## Recap of Data Manipulation with the tidyverse

...

---

## Handling Missing Data

...

---

## Data Transformation

...

---

## Handling Categorical Variables

...

---

## Combining and Merging Datasets

...

---

## Case Study and Practical Exercises

...

---

class: middle

# Hour 3: Data Visualization and Communication

---

## Introduction to Data Visualization

...

---

## Introduction to ggplot2

...

---

## Creating Basic Visualizations

...

---

## Customizing Plots

...

---

## Creating Advanced Visualizations

...

---

## Interactive Visualizations

...

---

## Best Practices for Data Visualization

...

---

## Hands-on Exercise: Data Visualization

...

---

class: middle

# Wrapping Up

...
```
